### ISSUE TITLE
Original repo of TSM?

### ISSUE THREAD

**Issue by Mape6** [billbo99/train-pubsub#1]
Hi Billbo99,

I have found your name in the changelog of the last TSM version 1.1.11. I'm curious where is the original repo of TSM? Is the mod still under developing? Or do you fix bugs and errors only?

Kind regards
mape

**Comment by billbo99** [comment]
Lordktor has for the moment given up playing Factorio and supporting TSM as a result.

I got him to allow me "contrib" access so I could fix bugs as they came up.

no idea where the original code was located,  I think he used another version control software package.
